<a href="https://colab.research.google.com/github/achu-narayan-s/Internship/blob/main/datatrained_practice_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Revising recent taught topics

In [1]:
pip install pandas

In [2]:
import numpy as np

# pandas
import pandas as pd

# matplotlib
import matplotlib.pyplot as plt

# scipy
import scipy

# scikit-learn
from sklearn import *

# tensorflow
import tensorflow as tf

# keras
import keras

# pytorch
import torch

# statsmodels
import statsmodels.api as sm

# networkx
import networkx as nx

# beautifulsoup4
from bs4 import BeautifulSoup

# requests
import requests

# flask
from flask import Flask

# sqlalchemy
import sqlalchemy

# pytest
import pytest

# tkinter
import tkinter as tk

# pygame
import pygame

# openpyxl
import openpyxl

pygame 2.5.0 (SDL 2.28.0, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [26]:
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

In [9]:
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/DSData/master/Advertising.csv"
data = pd.read_csv(url)

# Split the data into input (X) and target (y) variables
X = data.drop("sales", axis=1)  # All columns except the "Sales" column
y = data["sales"]  # Target variable ("Sales" column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Ridge regression model
model = Ridge(alpha=1.0)  # You can adjust the value of alpha (regularization strength) as needed

# Fit the model to the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 3.1990018641043965


In [10]:
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/DSData/master/Advertising.csv"
data = pd.read_csv(url)

# Split the data into input (X) and target (y) variables
X = data.drop("sales", axis=1)  # All columns except the "Sales" column
y = data["sales"]  # Target variable ("Sales" column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Lasso regression model
model = Lasso(alpha=1.0)  # You can adjust the value of alpha (regularization strength) as needed

# Fit the model to the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 3.1513524142973472


In [11]:
import pandas as pd
import math

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/DSData/master/Advertising.csv"
data = pd.read_csv(url)

# Extract the target variable
sales = data["sales"]

# Count the occurrences of each unique value in the target variable
value_counts = sales.value_counts()

# Calculate the total number of samples
total_samples = len(sales)

# Calculate the entropy
entropy = 0
for count in value_counts:
    probability = count / total_samples
    entropy -= probability * math.log2(probability)

# Print the entropy
print("Entropy:", entropy)

Entropy: 6.752965862251104


In [12]:
import pandas as pd

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/DSData/master/Advertising.csv"
data = pd.read_csv(url)

# Extract the target variable
sales = data["sales"]

# Count the occurrences of each unique value in the target variable
value_counts = sales.value_counts()

# Calculate the total number of samples
total_samples = len(sales)

# Calculate the probability of each value occurrence
probabilities = value_counts / total_samples

# Calculate the squared probabilities
squared_probabilities = probabilities ** 2

# Calculate the Gini coefficient
gini_coefficient = 1 - squared_probabilities.sum()

# Print the Gini coefficient
print("Gini Coefficient:", gini_coefficient)

Gini Coefficient: 0.9896


In [14]:
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/DSData/master/SBI_Life_insurance.csv"
data = pd.read_csv(url)

# Split the data into input (X) and target (y) variables
X = data.drop("charges", axis=1)  # All columns except the "TARGET" column
y = data["charges"]  # Target variable ("TARGET" column)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Ridge regression model
model = Ridge(alpha=1.0)  # You can adjust the value of alpha (regularization strength) as needed

# Fit the model to the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 33785160.28006716


In [22]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/dataset4/main/Grades.csv"
data = pd.read_csv(url)

# Drop the "Seat no." column
data = data.drop("Seat No.", axis=1)

# Split the data into input (X) and target (y) variables
X = data.iloc[:, :-1]  # All columns except the last one
y = data.iloc[:, -1]   # Last column (target variable)

# Identify categorical columns for one-hot encoding
categorical_cols = X.select_dtypes(include=['object']).columns

# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer([('encoder', OneHotEncoder(handle_unknown='ignore'), categorical_cols)], remainder='passthrough')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocess the data
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# Create a Linear Regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train_encoded, y_train)

# Predict on the test data
y_pred = model.predict(X_test_encoded)

# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 0.03460080761500847


In [25]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/dataset4/main/Grades.csv"
data = pd.read_csv(url)

# Drop the "Seat no." column
data = data.drop("Seat No.", axis=1)

# Split the data into input (X) and target (y) variables
X = data.iloc[:, :-1]  # All columns except the last one
y = data.iloc[:, -1]   # Last column (target variable)

# Identify categorical columns for one-hot encoding
categorical_cols = X.select_dtypes(include=['object']).columns

# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer([('encoder', OneHotEncoder(handle_unknown='ignore'), categorical_cols)], remainder='passthrough')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocess the data
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# Create a Random Forest Regression model
model = RandomForestRegressor()

# Fit the model to the training data
model.fit(X_train_encoded, y_train)

# Predict on the test data
y_pred = model.predict(X_test_encoded)

# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 0.027702293379130445


In [43]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Read the CSV file into a DataFrame
url = "https://raw.githubusercontent.com/dsrscientist/dataset4/main/Japan_used_cars_datasets.csv"
data = pd.read_csv(url)

# Preprocess the data
X = data.drop("price", axis=1)  # Input features (all columns except "Price")
y = data["price"]               # Target variable ("Price")

# Identify categorical columns for one-hot encoding
categorical_cols = X.select_dtypes(include=['object']).columns

# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer([('encoder', OneHotEncoder(handle_unknown='ignore'), categorical_cols)], remainder='passthrough')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocess the data using one-hot encoding
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# Create a Decision Tree Classifier
model = DecisionTreeClassifier()

# Fit the model to the training data
model.fit(X_train_encoded, y_train)

# Predict on the test data
y_pred = model.predict(X_test_encoded)

# Create a confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 6]]
